### ISSUE TITLE
consider the inclusion of concatenation modes for 0-* type occurrences in an instance of a FHIR resource

### ISSUE THREAD

**Issue by SaulLu** [arkhn/FHIR2Dataset#30]
A feature has been implemented to specify how to concatenate the elements to be retrieved in an instance of a FHIR resource. 
These 3 possibilities are:
* cell: the results are stroked in a list.
* row: a new row is created for each new result.
* col: a new column is created for each new result.

For now, the settings are hard-coded: all ids (instance id and references) are row type and the others are cell type. We should see if we can leave the choice in the configuration file.

**Comment by MarionBla** [comment]
by default the list view will be used by v0.2
