### ISSUE TITLE
Find a way to make the notebook comparison more readable between commits

### ISSUE THREAD

**Issue by SaulLu** [arkhn/FHIR2Dataset#48]

**Comment by Jasopaum** [comment]
I never set it up by myself but are you looking for something like https://www.reviewnb.com/?

**Comment by SaulLu** [comment]
This is exactly the kind of solution I was hoping for! Thank you very much. I'm looking into it.

**Comment by SaulLu** [comment]
The feature has been added! We can now use `reviewNB` to comment on our notebook changes :smile: 
@MarionBla @LaRiffle
